### DISCUSSION TITLE
Opening nnn in alacritty by keyboard shortcut bypasses tmux session

### DISCUSSION THREAD

**Discussion by sbushmanov** [jarun/nnn#1743] [Q&A] [answered]
I have alacritty + tmux and everything works fine when I start `nnn` in an opened terminal.

However, when I try to assign a keyboard shortcut to `alacritty -e nnn -e` some functionality involving `tmux` is broken, e.g. `preview-tui`: binary files preview is shown in another `alacritty` terminal on top of original, directory preview does not show up.

I've been able to pinpoint the problem to `tmux` not getting started along with `alacritty`, i.e. there is no `tmux` session when I start `alacritty -e nnn -e` from another `gnome-terminal` instance. However, when I simply start `alacritty` and afterwards start `nnn -e` everything works as expected (and `tmux` session is started indeed).

So my question is: "What is so special about `alacritty -e nnn -e` command that it bypasses `tmux`?

The top of my `alacritty` config looks like this:

```
#~/.config/alacritty/alacritty.yml
shell:
  program: /usr/bin/tmux
  args:
  - new-session
  - -A
  - -D
  - -s
  - main
```
